language: node_js
node_js:
- 5.1.0
deploy:
  provider: npm
  email: mrstebouk@gmail.com
  api_key:
    secure: tr3hDznJOHmPhNr04/YsVPD+DwpeEx9LYt8U0eCrfsbThWIKCNP++QOTG01AD0Zk76mIK5qgR89dwwSzFwweaq4UdrnpUbX8dpW/8B7Qgd5X399JPz1F+8PyyZrsLihRC4j2Aa9yhW3ba7V2Kz/07L88CYrwIbB0W/QIVrNmg8hthXpEOq3FP/KjlFoNAbmevuymMXAduXvcXCmIjaggYdwd5zj25srMN++/L2Zn7mJ66iQerZ9/UqWnkb1CnSuoKxqK8UqmWmbHxfjolyTFuatVHnw8tsHXEMeP6NzoLiKZoNvJS0hDA4ZmFs/O9Y4J27g+EE7ChyADrnqPwFdMdsNtZQ3Y28d9XhIsMAI0EYCqzwKqpXHdtLVxD0ImZCKNCrgg9lLc7u1HIfbzPY3lbe0AqFD+JziEWj3KIwuJZOYfQiZaI0YC0RFSk2A+Nq4iMiGhT1QhCoTTnAShlGClb7ZmWgFVapB3pfWiSPSD3aclHc2zpQV7kSwMtTw+scBJIRigQqPfeXV9ZK69wIo6rFXF2DQPRNH9boWN/jMCqLJuFNmql7AgGT2YfUIlVt8o1u6ChlNLJNta7lY9AsMF0ZkkYLCV0qkE5YsCbYKtle29skTPD8vbYvUV966TIpWtIV0D017rFeeXShuE/ZMDSqQ9yIUmHq4P9XNTObXbrYY=
  on:
    tags: true
    repo: mrstebo/node-env-config-file-loader
